# Generated by Django 5.2 on 2025-05-05 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collab',
            name='participants',
            field=models.IntegerField(default=0),
        ),
    ]
